flysystem:
    storages:
        documents.storage:
            adapter: 'aws'
            options:
                client: 'minio.client'
                bucket: '%env(MINIO_BUCKET_DOCUMENTS)%'
                prefix: ''
                
        templates.storage:
            adapter: 'aws'
            options:
                client: 'minio.client'
                bucket: '%env(MINIO_BUCKET_TEMPLATES)%'
                prefix: ''

services:
    minio.client:
        class: Aws\S3\S3Client
        arguments:
            - endpoint: '%env(MINIO_ENDPOINT)%'
              credentials:
                key: '%env(MINIO_KEY)%'
                secret: '%env(MINIO_SECRET)%'
              region: '%env(MINIO_REGION)%'
              version: 'latest'
              use_path_style_endpoint: true