flysystem:
    storages:
        documents.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/documents'
                
        templates.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/templates'
