knp_paginator:
  page_range: 5
  default_options:
    page_name: page
    default_limit: 10
    distinct: false
    sort_direction_name: order
  template:
    pagination: knpPaginator/pagination/custom_bootstrap_v5_pagination.html.twig
