knpu_oauth2_client:
    clients:
        microsoft:
            type: generic
            provider_class: TheNetworg\OAuth2\Client\Provider\Azure
            client_id: '%env(MICROSOFT_CLIENT_ID)%'
            client_secret: '%env(MICROSOFT_CLIENT_SECRET)%'
            provider_options:
                tenant: 'common'
                scope: 'openid profile email Tasks.ReadWrite Tasks.ReadWrite.Shared https://graph.microsoft.com/Tasks.ReadWrite https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Calendars.ReadWrite'
            redirect_route: connect_microsoft_check
            redirect_params: {}