league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:JWT_SECRET_KEY)%'
        private_key_passphrase: '%env(JWT_PASSPHRASE)%'
        encryption_key: '%env(OAUTH_ENCRYPTION_KEY)%'
        enable_auth_code_grant: true
        enable_refresh_token_grant: true
    resource_server:
        public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    scopes:
        available: ['crm:read']
        default: ['crm:read']
    persistence:
        doctrine: null

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
