when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false
        register_error_handler: false
        options:
            traces_sample_rate: 0.0
            environment: '%env(APP_ENV)%'
            release: '%env(APP_VERSION)%'
            http_connect_timeout: 1
            http_timeout: 1
            ignore_exceptions:
                - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'

    services:
        Sentry\Monolog\Handler:
            arguments:
                $hub: '@Sentry\State\HubInterface'
                $fillExtraContext: true

        Monolog\Processor\PsrLogMessageProcessor:
            tags: { name: monolog.processor, handler: sentry }
