<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312155607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial PostgreSQL schema - migrated from MySQL';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE calendar_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, microsoft_event_id VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, category VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, microsoft_last_modified_date_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_cancelled BOOLEAN NOT NULL, is_archived BOOLEAN NOT NULL, contact_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57FA09C9E7A1254A ON calendar_event (contact_id)');
        $this->addSql('CREATE INDEX IDX_57FA09C9B03A8386 ON calendar_event (created_by_id)');
        $this->addSql('CREATE INDEX IDX_57FA09C99395C3F3 ON calendar_event (customer_id)');
        $this->addSql('CREATE INDEX idx_microsoft_event_id ON calendar_event (microsoft_event_id)');
        $this->addSql('CREATE INDEX idx_start_date_time ON calendar_event (start_date_time)');
        $this->addSql('CREATE INDEX idx_created_by_customer ON calendar_event (created_by_id, customer_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MICROSOFT_EVENT_ID ON calendar_event (microsoft_event_id)');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526C9395C3F3 ON comment (customer_id)');
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, position VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, mobile_phone VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, address_number VARCHAR(10) DEFAULT NULL, address_street VARCHAR(255) DEFAULT NULL, address_postal_code VARCHAR(10) DEFAULT NULL, address_city VARCHAR(100) DEFAULT NULL, is_primary BOOLEAN NOT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E6389395C3F3 ON contact (customer_id)');
        $this->addSql('CREATE INDEX idx_contact_name ON contact (first_name, last_name)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, lead_origin VARCHAR(100) DEFAULT NULL, origin VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, address_number VARCHAR(10) DEFAULT NULL, address_street VARCHAR(255) DEFAULT NULL, address_postal_code VARCHAR(10) DEFAULT NULL, address_city VARCHAR(100) DEFAULT NULL, action VARCHAR(255) DEFAULT NULL, worth VARCHAR(255) DEFAULT NULL, commision VARCHAR(255) DEFAULT NULL, margin VARCHAR(255) DEFAULT NULL, company_group VARCHAR(255) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, canal_signature VARCHAR(255) DEFAULT NULL, legal_form VARCHAR(50) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_customer_status ON customer (status)');
        $this->addSql('CREATE INDEX idx_customer_name ON customer (name)');
        $this->addSql('CREATE INDEX idx_customer_siret ON customer (siret)');
        $this->addSql('CREATE INDEX idx_customer_user ON customer (user_id)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, customer_id INT NOT NULL, type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A769395C3F3 ON document (customer_id)');
        $this->addSql('CREATE INDEX IDX_D8698A76C54C8C93 ON document (type_id)');
        $this->addSql('CREATE TABLE document_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE energy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, contract_end DATE DEFAULT NULL, power_kva INT DEFAULT NULL, segment VARCHAR(255) DEFAULT NULL, peak_consumption DOUBLE PRECISION DEFAULT NULL, hph_consumption DOUBLE PRECISION DEFAULT NULL, hch_consumption DOUBLE PRECISION DEFAULT NULL, hpe_consumption DOUBLE PRECISION DEFAULT NULL, hce_consumption DOUBLE PRECISION DEFAULT NULL, base_consumption DOUBLE PRECISION DEFAULT NULL, hp_consumption DOUBLE PRECISION DEFAULT NULL, hc_consumption DOUBLE PRECISION DEFAULT NULL, profile VARCHAR(255) DEFAULT NULL, transport_rate VARCHAR(255) DEFAULT NULL, total_consumption DOUBLE PRECISION DEFAULT NULL, customer_id INT NOT NULL, fta_id INT DEFAULT NULL, energy_provider_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_971179919395C3F3 ON energy (customer_id)');
        $this->addSql('CREATE INDEX IDX_9711799179A787AF ON energy (fta_id)');
        $this->addSql('CREATE INDEX IDX_9711799140637D70 ON energy (energy_provider_id)');
        $this->addSql('CREATE INDEX idx_energy_contract_end ON energy (contract_end)');
        $this->addSql('CREATE INDEX idx_energy_code ON energy (code)');
        $this->addSql('CREATE TABLE energy_provider (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE fta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, fixed_cost DOUBLE PRECISION NOT NULL, power_reservation_peak DOUBLE PRECISION NOT NULL, power_reservation_hph DOUBLE PRECISION NOT NULL, power_reservation_hch DOUBLE PRECISION NOT NULL, power_reservation_hpe DOUBLE PRECISION NOT NULL, power_reservation_hce DOUBLE PRECISION NOT NULL, consumption_peak DOUBLE PRECISION NOT NULL, consumption_hph DOUBLE PRECISION NOT NULL, consumption_hch DOUBLE PRECISION NOT NULL, consumption_hpe DOUBLE PRECISION NOT NULL, consumption_hce DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE import (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_rows INT NOT NULL, processed_rows INT NOT NULL, success_rows INT NOT NULL, error_rows INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_import_status ON import (status)');
        $this->addSql('CREATE INDEX idx_import_created_at ON import (created_at)');
        $this->addSql('CREATE INDEX idx_import_user_id ON import (user_id)');
        $this->addSql('CREATE INDEX idx_import_type ON import (type)');
        $this->addSql('CREATE TABLE import_analysis_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operation_type VARCHAR(50) NOT NULL, entity_type VARCHAR(100) NOT NULL, count INT NOT NULL, details JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, import_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_import_analysis_result_import_id ON import_analysis_result (import_id)');
        $this->addSql('CREATE INDEX idx_import_analysis_result_operation_type ON import_analysis_result (operation_type)');
        $this->addSql('CREATE TABLE import_error (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "row_number" INT NOT NULL, severity VARCHAR(50) NOT NULL, message TEXT NOT NULL, field_name VARCHAR(100) DEFAULT NULL, row_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, import_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_import_error_import_id ON import_error (import_id)');
        $this->addSql('CREATE INDEX idx_import_error_severity ON import_error (severity)');
        $this->addSql('CREATE TABLE microsoft_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, access_token TEXT NOT NULL, refresh_token TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scope VARCHAR(255) DEFAULT NULL, microsoft_email VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C64E8AA76ED395 ON microsoft_token (user_id)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, document_type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97601F8361232A4F ON template (document_type_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, profile_picture VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, signature TEXT DEFAULT NULL, default_calendar_id VARCHAR(255) DEFAULT NULL, timezone VARCHAR(50) NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649979B1AD6 ON "user" (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C99395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6389395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A769395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76C54C8C93 FOREIGN KEY (type_id) REFERENCES document_type (id)');
        $this->addSql('ALTER TABLE energy ADD CONSTRAINT FK_971179919395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE energy ADD CONSTRAINT FK_9711799179A787AF FOREIGN KEY (fta_id) REFERENCES fta (id)');
        $this->addSql('ALTER TABLE energy ADD CONSTRAINT FK_9711799140637D70 FOREIGN KEY (energy_provider_id) REFERENCES energy_provider (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import ADD CONSTRAINT FK_9D4ECE1DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import_analysis_result ADD CONSTRAINT FK_8A8C26C2B6A263D9 FOREIGN KEY (import_id) REFERENCES import (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import_error ADD CONSTRAINT FK_B08813BFB6A263D9 FOREIGN KEY (import_id) REFERENCES import (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE microsoft_token ADD CONSTRAINT FK_7C64E8AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F8361232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9E7A1254A');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9B03A8386');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C99395C3F3');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C9395C3F3');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E6389395C3F3');
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09A76ED395');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A769395C3F3');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76C54C8C93');
        $this->addSql('ALTER TABLE energy DROP CONSTRAINT FK_971179919395C3F3');
        $this->addSql('ALTER TABLE energy DROP CONSTRAINT FK_9711799179A787AF');
        $this->addSql('ALTER TABLE energy DROP CONSTRAINT FK_9711799140637D70');
        $this->addSql('ALTER TABLE import DROP CONSTRAINT FK_9D4ECE1DA76ED395');
        $this->addSql('ALTER TABLE import_analysis_result DROP CONSTRAINT FK_8A8C26C2B6A263D9');
        $this->addSql('ALTER TABLE import_error DROP CONSTRAINT FK_B08813BFB6A263D9');
        $this->addSql('ALTER TABLE microsoft_token DROP CONSTRAINT FK_7C64E8AA76ED395');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE template DROP CONSTRAINT FK_97601F8361232A4F');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649979B1AD6');
        $this->addSql('DROP TABLE calendar_event');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_type');
        $this->addSql('DROP TABLE energy');
        $this->addSql('DROP TABLE energy_provider');
        $this->addSql('DROP TABLE fta');
        $this->addSql('DROP TABLE import');
        $this->addSql('DROP TABLE import_analysis_result');
        $this->addSql('DROP TABLE import_error');
        $this->addSql('DROP TABLE microsoft_token');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE template');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
